apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: load-test-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      type: string
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      type: string
    - name: imageUrl
      description: Url of image repository
      type: string
    - name: imageTag
      description: Tag to apply to the built image
      type: string
  tasks:
  - name: build-push-image
    taskRef:
      name: load-test
    params:
      - name: IMAGE
        value: "$(params.IMAGE)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: microservice-deploy
    taskRef:
      name: load-test-deploy
    runAfter:
      - build-push-image
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
