apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: level3
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/nbaghanim/project-level3
