apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: orders-pipelinerun 
spec:
  pipelineRef:
    name: orders-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: orders-resource
  params:
    - name: CONTEXT
      value: "/workspace/level3-project/orders"
    - name: DOCKERFILE
      value: "/workspace/level3-project/orders/Dockerfile"
    - name: IMAGE
      value: "nbaghanim/orders"
    - name: pathToYamlFile
      value: "level3-project/deployment/orders/orders-dep.yaml"
    - name: imageUrl
      value: "nbaghanim/orders"
    - name: imageTag
      value: "latest"
    - name: pathToYamlFile-db
      value: "level3-project/deployment/orders/orders-db-dep.yaml"
    - name: imageUrl-db
      value: "mongo"
    - name: imageTag-db
      value: "latest"
      
  serviceAccountName: nbaghanim-docker-hub
