apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: e2e-
spec:
  serviceAccountName: nbaghanim-docker-hub
  params:
  - name: IMAGE
    value: "nbaghanim/e2e-test"
  - name: CONTEXT
    value: "/workspace/level3-project/e2e-js-test"
  - name: DOCKERFILE
    value: "/workspace/level3-project/e2e-js-test/Dockerfile"
  pipelineRef:
    name: build-only
  resources:
  - name: level3-project
    resourceRef:
      name: level3
