apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: role-binding-socks-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-socks-shop
subjects:
  - kind: ServiceAccount
    name: nbaghanim-docker-hub
