apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-run-ingress
spec:
  resources:
  - name: level3-project
    type: git
  params:
  - name: IMAGE
    type: string
  - name: pathToYamlFile
    type: string
  - name: pathToServiceFile
    type: string
  - name: namespace
    type: string
  - name: CONTEXT
    type: string
  - name: DOCKERFILE
    type: string
  - name: pathToIngressFile
    type: string
  tasks:
  - name: build-push
    taskRef:
      name: build-push
    params:
    - name: IMAGE
      value: "$(params.IMAGE)"
    - name: CONTEXT
      value: "$(params.CONTEXT)"
    - name: DOCKERFILE
      value: "$(params.DOCKERFILE)"
    resources:
      inputs:
      - name: level3-project
        resource: level3-project
  - name: run-image
    taskRef:
      name: deploy-using-kubectl-with-ingress
    runAfter:
      - build-push
    params:
    - name: pathToYamlFile
      value: "$(params.pathToYamlFile)"
    - name: pathToServiceFile
      value: "$(params.pathToServiceFile)"
    - name: pathToIngressFile
      value: "$(params.pathToIngressFile)"
    - name: image
      value: "$(params.IMAGE)"
    - name: namespace
      value: "$(params.namespace)"
    resources:
      inputs:
      - name: level3-project
        resource: level3-project
