apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: e2e-tests-resource
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/nbaghanim/project-level3
