apiVersion: v1
kind: ConfigMap
metadata:
  name: config-artifact-bucket
data:
  location: s3://tektonbucket
  bucket.service.account.secret.name: tekton-storage
  bucket.service.account.secret.key: boto-config
  bucket.service.account.field.name: BOTO_CONFIG
