apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-test
  labels:
    name: e2e-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: e2e-test
  template:
    metadata:
      labels:
        name: e2e-test
    spec:
      containers:
      - name: e2e-test
        image:  __IMAGE__
        command: ["/bin/sh"]
        args: ["-c","/app/runner.sh"]
      nodeSelector:
        beta.kubernetes.io/os: linux
