apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: front-end-pipelinerun 
spec:
  serviceAccountName: nbaghanim-docker-hub
  pipelineRef:
    name: front-end-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: front-end-resource
 
