apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: front-end-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  tasks:
  - name: build-push-image
    taskRef:
      name: front-end
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: deploy-socks-shop
    taskRef:
      name: front-end-deploy
    runAfter:
      - build-push-image
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
