apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task-prod
spec:
  resources:
    inputs:
    - name: level3-project
      type: git
  params:
  - name: pathToYamlFile
  steps:
  - name: update-yaml
    image: alpine
    command: ["sed"]
    args:
      - "-i"
      - "-e"
      - "s;__IMAGE__;$(inputs.params.imageUrl):$(inputs.params.imageTag);g"
      - "/workspace/$(inputs.params.pathToYamlFile)"
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ["kubectl"]
    args:
      - "apply"
      - "-f"
      - "/workspace/$(inputs.params.pathToYamlFile)"
      - "-n"
      - "prod"
