apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: e2e-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/e2e-test"
  - name: pathToYamlFile
    value: "./e2e-js-test/e2e-dep.yaml"
  - name: namespace
    value: "test"
  - name: CONTEXT
    value: "/workspace/level3-project/e2e-js-test"
  - name: DOCKERFILE
    value: "/workspace/level3-project/e2e-js-test/Dockerfile"
  pipelineRef:
    name: build-deploy-run-test
  resources:
  - name: level3-project
    resourceRef:
      name: level3
