apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: deploy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy-role
subjects:
  - kind: ServiceAccount
    name: nbaghanim-docker-hub
    namespace: tekton-pipelines
