apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catalogue-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      type: string
    - name: IMAGE-db
      description: Name (reference) of the database image to build.
      type: string
    - name: pathToYamlFile
      description: The path to the yaml file to deploy
      type: string
    - name: imageUrl
      description: Url of image repository
      type: string
    - name: imageTag
      description: Tag to apply to the built image
      type: string
    - name: pathToYamlFile-db
      description: The path to the database yaml file to deploy
      type: string
    - name: imageUrl-db
      description: Url of image repository
      type: string
    - name: imageTag-db
      description: Tag to apply to the image
      type: string
  tasks:
  - name: build-push-image-db
    taskRef:
      name: catalogue-db
    params:
      - name: IMAGE
        value: "$(params.IMAGE-db)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: run-db-image
    taskRef:
      name: catalogue-db-deploy
    runAfter:
      - build-push-image-db
    params:
      - name: pathToYamlFile-db
        value:  "$(params.pathToYamlFile-db)"
      - name: imageUrl-db
        value: "$(params.imageUrl-db)"
      - name: imageTag-db
        value: "$(params.imageTag-db)"
    resources: 
      inputs:
        - name: level3-project
          resource: level3-project  
  - name: build-push-image
    taskRef:
      name: catalogue
    runAfter:
      - build-push-image-db      
      - run-db-image
    params:
      - name: IMAGE
        value: "$(params.IMAGE)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: microservice-deploy
    taskRef:
      name: catalogue-deploy
    runAfter:
      - build-push-image-db
      - run-db-image
      - build-push-image
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
