apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: payment-runner
spec:
  serviceAccountName: payment-docker-hub
  taskRef:
    name: payment
  params:
  - name: IMAGE
    value: "nbaghanim/payment"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: payment-resource
